(TeX-add-style-hook "4_contre_ex"
 (lambda ()
    (LaTeX-add-labels
     "fig:illustration"
     "sec:intuition"
     "ex:intuition"
     "sec:RE-automaton"
     "def:re-automaton"
     "def:xrw_alpha"
     "th:equiv"
     "def:well-defined"
     "ex:pruning"
     "def:resolution_cp"
     "def:normalisation"
     "ex:inj_contrex"
     "prop:norm_determinism"
     "prop:norm_injectivity"
     "prop:norm_representant"
     "prop:norm_well_def"
     "sec:filtrage"
     "def:matching-algorithm"
     "prop:matching-complete"
     "eq:1"
     "prop:matching-correct"
     "lemma:C-well-defined"
     "one"
     "two"
     "thm:C"
     "thm:W"
     "ex:W"
     "intersection:sec"
     "def:reachable-states"
     "sec:refinement"
     "subsec:refinementstep"
     "sec:exact"
     "thm:regular")
    (TeX-add-symbols
     "xrwa"
     "xrwap")
    (TeX-run-style-hooks
     "4_contre_ex/semantics_ex"
     "4_contre_ex/img/refine")))

