(TeX-add-style-hook "report"
 (lambda ()
    (LaTeX-add-bibliographies
     "sabbrev"
     "eureca"
     "genet")
    (LaTeX-add-environments
     "definition"
     "example"
     "theorem"
     "lemma"
     "proof")
    (LaTeX-add-labels
     "sec:conclusion")
    (TeX-add-symbols
     "switchlstcoq"
     "lstlanguagefiles")
    (TeX-run-style-hooks
     "listings"
     "alltt"
     "inputenc"
     "latin1"
     "bussproofs"
     "amsfonts"
     "amssymb"
     "amsmath"
     "latexsym"
     "stmaryrd"
     "xypic"
     "curve"
     "RR"
     "latex2e"
     "art10"
     "article"
     "rapinclude2"
     "intro"
     "preliminaries"
     "completion"
     "objectives"
     "rewriting"
     "automata"
     "inclusion"
     "closure"
     "benchs")))

